### ISSUE TITLE
Make compatible with other Ruby implementations

### ISSUE THREAD

**Issue by chrisseaton** [ko1/rstfilter#2]
TruffleRuby doesn't support `RubyVM`, as per the MRI documentation.

I got `rstfilter` basically working on TruffleRuby with this hack:

```patch
diff --git a/exe/rstfilter b/exe/rstfilter
old mode 100644
new mode 100755
diff --git a/exe/rstfilter-lsp b/exe/rstfilter-lsp
old mode 100644
new mode 100755
diff --git a/lib/rstfilter/rewriter.rb b/lib/rstfilter/rewriter.rb
index 3f7ac84..36a6332 100644
--- a/lib/rstfilter/rewriter.rb
+++ b/lib/rstfilter/rewriter.rb
@@ -153,9 +153,8 @@ module RstFilter
     def rewrite src, filename
       # check syntax
       prev_v, $VERBOSE = $VERBOSE, false
-      ast = RubyVM::AbstractSyntaxTree.parse(src)
       $VERBOSE = prev_v
-      last_lineno = ast.last_lineno
+      last_lineno = src.lines.size - 1
 
       # rewrite
       src           = src.lines[0..last_lineno].join # remove __END__ and later
```

(Note that therefore this code doesn't seem to be exercised by the tests.)

I'm not sure if we can use `parser` to find the last line?

`test_mod_src_self` and `test_mod_src_ruby` don't work as they also reference RubyVM. I'm not really sure what these two tests do though?

I'd be great to get `rstfilter` working on alternative Rubies, since it can be used to compare outputs. I think JRuby also doesn't support RubyVM, but I'm not sure.

@eregon, @headius.

**Comment by ko1** [comment]
It is used to cut off the `__END__` because parser.gem consumes huge time with huge text after `__END__`.
There is no reason to use `RubyVM` if there is a technique to achieve it.

**Comment by ko1** [comment]
or `if defined? RubyVM` is acceptable.

**Comment by chrisseaton** [comment]
Sorry I'm not sure what you're wanting here - you closed as completed, but there's no new commits.

Are you saying you aren't interested in a fix, or are you saying that Ruby implementations should be implementing `RubyVM`, or are you saying you think it's not an issue for some reason I don't understand?

**Comment by ko1** [comment]
* Your patch is not acceptable because this code is needed (https://github.com/ko1/rstfilter/issues/2#issuecomment-1172941333) so I closed this ticket.
* Skip `RubyVM` lines is acceptable (https://github.com/ko1/rstfilter/issues/2#issuecomment-1172941635)

**Comment by chrisseaton** [comment]
> Your patch is not acceptable

But I haven't proposed adding a patch. This isn't a PR - it's an issue. The patch just explains my question about what is needed.

> Skip RubyVM lines is acceptable

Ok - but you won't accept that?

I don't understand - you've closed the issue but we haven't resolved it?

**Comment by ko1** [comment]
> But I haven't proposed adding a patch. This isn't a PR - it's an issue. The patch just explains my question about what is needed.

Ah, I misunderstood (it is not a PR).

> Ok - but you won't accept that?

I'll accept if PR is available.

**Comment by chrisseaton** [comment]
I did some more investigation about what this code does - I can't really reproduce it taking a huge time to parse a file with a large data section.

I tried with a 1 GB `DATA` payload, and yeah it takes 14s to process it, but are you regularly running on files this large? A 100 MB `DATA` takes such a second or so.

The other issue is it breaks scripts - if a file has `DATA`, it's probably going to reference it, and at the moment your setup makes it do

```ruby
DATA.read.bytesize                                 #=> raised #<NameError: uninitialized constant DATA>
__END__
xxxxxxxxxxx
```

So removing `DATA` breaks programs, doesn't seem to achieve anything very useful in practice, and isn't implemented in a way compatible with other Ruby VMs.

Is it really critical to keep, or would it improve several things if we just removed it?

**Comment by ko1** [comment]
```patch
diff --git a/lib/rstfilter/rewriter.rb b/lib/rstfilter/rewriter.rb
index 3f7ac84..c134376 100644
--- a/lib/rstfilter/rewriter.rb
+++ b/lib/rstfilter/rewriter.rb
@@ -151,11 +151,15 @@ module RstFilter
     end

     def rewrite src, filename
-      # check syntax
-      prev_v, $VERBOSE = $VERBOSE, false
-      ast = RubyVM::AbstractSyntaxTree.parse(src)
-      $VERBOSE = prev_v
-      last_lineno = ast.last_lineno
+      if ENV['CUT_END']
+        # check syntax
+        prev_v, $VERBOSE = $VERBOSE, false
+        ast = RubyVM::AbstractSyntaxTree.parse(src)
+        $VERBOSE = prev_v
+        last_lineno = ast.last_lineno
+      else
+        last_lineno = src.lines.size
+      end

       # rewrite
       src           = src.lines[0..last_lineno].join # remove __END__ and later
```

```
$ wc ~/src/rb/t.rb
 119758  304897 2747889 /home/ko1/src/rb/t.rb

$ time exe/rstfilter ~/src/rb/t.rb
(snip)
real    1m17.988s
user    1m15.687s
sys     0m1.453s

$ time CUT_END=true exe/rstfilter ~/src/rb/t.rb

_a = :hello                                        #=> :hello


real    0m0.525s
user    0m0.286s
sys     0m0.037s
```

Note: `~/src/rb/t.rb` is located windows host and rstfilter runs on WSL, so storage is slow.
Note2: t.rb is growing ruby script with `__END__` like:

```ruby
rubyexpr

__END__

rubyexpr2

__END__

...
```

(1) put`__END__` and (2) write small script, and goto (1). Now it has 120k lines of Ruby codes.

On my survey, parser.gem starts parsing after `__END__` as Ruby script at `expression` method (maybe, I don't remember correctly).

Also, I think cutting down `__END__` is more kindly for users (especially for me). It can be controlled by command line option, though.

**Comment by ko1** [comment]
maybe parser.gem has ability to tell the `__END__` line, so if the feature is available we can use it instead of current impl,
